services:
  - type: web
    name: consultorio-digital
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: firebase-credentials.json
